name: Build Release version

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  build:
    if: startswith(${{ github.event.pull_request.head.ref }}, 'release-please') == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: "just echo ref"
        run: echo ${{github.event.pull_request.head.ref}}

      - name: "just echo merged"
        run: echo ${{github.event.pull_request.merged}}