name: Build Release 

on:
  pull_request:
    types: [closed]

permissions:
  contents: write

jobs:
  build:
    if: ${{github.event.pull_request.merged == true && startswith(github.event.pull_request.head.ref, 'release-please')}}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 # Required due to the way Git works, without it this action won't be able to find any or the correct tags
      - name: "Get latest tag"
        id: latesttag
        uses: "actions-ecosystem/action-get-latest-tag@v1"

      - name: "just echo ref"
        run: echo ${{github.event.pull_request.head.ref}}

      - name: "just echo tag"
        run: echo ${{steps.latesttag.outputs.tag}}
