on:
  push:
    branches:
      - main
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            command: manifest

      - name: "echo push commits"
        run: echo ${{github.event.commits[0].author.name}}

  build-release:
    if: ${{startswith(github.event.commits[0].author.name, 'github-actions')}}
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0 
      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: "just echo tag"
        run: echo ${{steps.previoustag.outputs.tag}}
      


