on:
  push:
    branches:
      - main
      - '!release-please*'
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            command: manifest

      - name: "echo push commits"
        run: echo ${{github.event.push.commits[0].message}}
